### ISSUE TITLE
Doesn't work.

### ISSUE THREAD

**Issue by masterofobzene** [loglux/remove_black_borders#2] opened 2024-02-05 19:54 UTC
Unfortunately your code doesn't seem to be working.

First I had problems with the folder paths, none of the input and output paths where working with the script, it just ignored them (I'm on windows 10). Had to workaround this by naming the input folder as the default "book", then it found the images.

Second, the script processes the images but they are like nothing happened. The white bars are still there. Modified the threshold for white and no changes at all, used values like 250 and as low as 10 to see if the scripts reacted in some way but failed. It outputs the images as they are in the input.

**Comment by loglux** [comment] 2024-02-05 20:37
I haven't encountered this folder path issue on my Windows 11, but I'll look closer.

To better understand and diagnose the image problem, please provide an example image where the script failed to remove the white bars as expected. This will significantly help me figure out the exact issue and make the necessary adjustments to the script.

**Comment by loglux** [comment] 2024-02-07 08:23
Duplicate of #1
I am closing this issue as it duplicates issue #1. Please feel free to direct any further comments or questions there. Thank you!

**Closed as completed** 2024-02-07 08:48 UTC
Labels: duplicate
